import { Download, ExternalLink, LockKeyhole, ShieldCheck } from 'lucide-react'

export function PrivacyContent({ offline = false }: { offline?: boolean }) {
  return <article className="mx-auto max-w-3xl space-y-8 py-6">
    <div><ShieldCheck className="mb-4 size-10 text-primary" /><p className="text-sm font-medium text-primary">Privacy you can inspect</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Your answers belong to you.</h1><p className="mt-4 text-lg leading-relaxed text-muted-foreground">Fourth Step saves your answers in an encrypted vault on this device. Your passphrase unlocks it here; it is never sent to us.</p></div>
    <section className="space-y-3 rounded-2xl border bg-card p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><LockKeyhole className="size-5 text-primary" />What protects your answers</h2><ul className="list-disc space-y-3 pl-5 text-sm leading-relaxed"><li>Sessions, unfinished answers, earlier entries, and support contacts are encrypted together before browser storage is written.</li><li>The app has no answer upload endpoint, account database, analytics, or owner dashboard for reading inventories. The owner cannot decrypt a saved vault without its passphrase.</li><li>Your key stays in memory while unlocked. Locking, closing the page, or 15 minutes without activity removes the app’s access to the key. Esc hides the screen; use Lock to end access.</li><li>Encryption uses AES-256-GCM with a fresh random nonce for every save. PBKDF2-SHA-256 derives the key with a random salt and 600,000 iterations. A long, unique passphrase still matters.</li></ul></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">What still requires trust</h2><p className="text-sm leading-relaxed text-muted-foreground">A website owner can change the code delivered on a future visit. Changed code could read answers while you unlock or type. Encryption alone cannot prove that a future version will behave safely. Malicious browser extensions, an unlocked device, and malware can also read what is on screen.</p><p className="text-sm leading-relaxed text-muted-foreground">The hosting provider may receive request metadata such as IP address, page path, and browser information when you visit the website. The current app does not put answers in those requests. Readable exports, printed pages, screenshots, and any copies you share are outside the encrypted vault.</p></section>
    <section className="space-y-3 rounded-2xl border bg-secondary/40 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><Download className="size-5 text-primary" />Choose your updates</h2><p className="text-sm leading-relaxed text-muted-foreground">The downloadable offline edition is one HTML file with the app included. Save it and open it locally. It makes no automatic network requests and has no automatic update mechanism. A saved copy cannot be silently replaced by a later website release. Only download an update when you choose.</p>{offline ? <p className="text-sm font-semibold text-primary">You are using the offline edition. Keep this file and make encrypted backups.</p> : <div className="flex flex-wrap gap-4 text-sm font-semibold text-primary"><a href="/downloads/fourthstep-offline.html" download className="underline underline-offset-4">Download offline edition</a><a href="/downloads/fourthstep-offline.sha256" download className="underline underline-offset-4">SHA-256 checksum</a></div>}<p className="text-xs leading-relaxed text-muted-foreground">Local-file storage behavior varies between browsers. Use a supported browser, keep the file in the same location, and download encrypted backups regularly. Clearing browser data removes the local vault. The checksum helps identify the downloaded file; it is not an independent security audit.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Keep a recovery copy</h2><p className="text-sm leading-relaxed text-muted-foreground">Download an encrypted backup from Your inventory. It includes unfinished work and contacts. Restore it in an empty browser profile or the offline edition with the same passphrase. Store your passphrase in a password manager or another secure place. We cannot reset it or recover answers if you lose it.</p><p className="text-sm leading-relaxed text-muted-foreground">If saving fails, locking leaves the page open and shows a recovery warning to protect unsaved work. Suspended browsers can delay auto-lock. After migration, earlier readable copies in device backups or browser history may still exist.</p></section>
    <section className="space-y-3 border-t pt-6"><h2 className="text-xl font-semibold">Evidence, with honest limits</h2><p className="text-sm leading-relaxed text-muted-foreground">The source and automated checks are public. Checks cover encryption, tampering, failed saves, migration, backups, and the offline file’s network restrictions. They provide useful evidence, but they are not an independent security review.</p><p className="rounded-xl bg-secondary p-4 text-sm font-semibold">Independent security audit: not yet completed.</p><div className="flex flex-wrap gap-4 text-sm font-semibold text-primary"><a href="https://github.com/gregcastro23/IV" target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 underline underline-offset-4">Inspect the source<ExternalLink className="size-3" /></a><a href="https://github.com/gregcastro23/IV/blob/main/SECURITY.md" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">Security design & review checklist</a><a href="https://github.com/gregcastro23/IV/actions" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">Automated check results</a></div></section>
  </article>
}
