import { Download, ExternalLink, Fingerprint, KeyRound, LockKeyhole, ShieldCheck } from 'lucide-react'

export function PrivacyContent({ offline = false }: { offline?: boolean }) {
  return <article className="mx-auto max-w-3xl space-y-8 py-6">
    <div><ShieldCheck className="mb-4 size-10 text-primary" /><p className="text-sm font-medium text-primary">Privacy you can inspect</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Your answers belong to you.</h1><p className="mt-4 text-lg leading-relaxed text-muted-foreground">Fourth Step saves your check-ins and inventory in an encrypted vault on this device. Only your keys open it, and they are never sent to us.</p></div>
    <section className="space-y-3 rounded-2xl border bg-card p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><LockKeyhole className="size-5 text-primary" />What protects your answers</h2><ul className="list-disc space-y-3 pl-5 text-sm leading-relaxed">
      <li>Check-ins (with their times), sessions, unfinished answers, earlier entries, settings, and support contacts are encrypted together before anything is written to browser storage.</li>
      <li>The app has no answer upload endpoint, account database, analytics, or owner dashboard. The site blocks the page from making network connections at all. The owner cannot decrypt your vault.</li>
      <li>Your inventory is encrypted with a random 256-bit key (AES-256-GCM, a fresh random nonce for every save). That key is itself locked separately by each way you unlock: your recovery key, each device you set up, and an optional PIN.</li>
      <li>Locking, closing the page, 15 minutes without activity, or being away longer than your chosen time removes the app’s access to the key. Switching apps hides the screen immediately. Esc hides it too.</li>
    </ul></section>
    <section className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Ways to unlock, and how strong each one is</h2>
      <div className="flex gap-3"><Fingerprint className="mt-0.5 size-5 shrink-0 text-primary" /><p className="text-sm leading-relaxed"><strong>Face, fingerprint, or device screen lock (recommended).</strong> A passkey on your device releases a secret only after your device verifies you, and that secret unlocks your vault. The secret lives in your device’s secure hardware (or your Apple or Google passkey manager) and limits guessing. Nothing is sent to a server. It works on this website only, not in the offline file.</p></div>
      <div className="flex gap-3"><KeyRound className="mt-0.5 size-5 shrink-0 text-primary" /><p className="text-sm leading-relaxed"><strong>PIN.</strong> Six or more digits, stored only in this browser and never in backups. After five wrong tries it turns itself off. It protects well against someone who picks up your phone. It is weaker against someone who copies this browser’s files, because a short PIN can be guessed offline. If that risk matters to you, use device unlock instead.</p></div>
      <div className="flex gap-3"><LockKeyhole className="mt-0.5 size-5 shrink-0 text-primary" /><p className="text-sm leading-relaxed"><strong>Recovery key.</strong> The master key (or a passphrase of at least 12 characters you chose). It opens your vault on any device and opens encrypted backups. A generated key has 100 random bits, which is far beyond guessing. You can replace it while you are unlocked. Old backups still open with the key that was current when they were made.</p></div>
    </section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">What still requires trust</h2><p className="text-sm leading-relaxed text-muted-foreground">A website owner can change the code delivered on a future visit. Changed code could read answers while you unlock or type. Encryption alone cannot prove that a future version will behave safely. Malicious browser extensions, an unlocked device, and malware can also read what is on screen.</p><p className="text-sm leading-relaxed text-muted-foreground">The hosting provider may receive request metadata such as IP address, page path, and browser information when you visit the website. The app does not put answers in those requests. A passkey entry named “Private vault” appears in your device’s password manager and shows this website’s address. Readable exports, CSV files, anything you paste into Google Docs, printed pages, screenshots, and copies you share are outside the encrypted vault.</p></section>
    <section className="space-y-3 rounded-2xl border bg-secondary/40 p-6"><h2 className="flex items-center gap-2 text-xl font-semibold"><Download className="size-5 text-primary" />Choose your updates</h2><p className="text-sm leading-relaxed text-muted-foreground">The downloadable offline edition is one HTML file with the app included. Save it and open it locally. It makes no automatic network requests and has no automatic update mechanism, so a later website release cannot silently replace it. Use your recovery key or a PIN there; device unlock needs the website.</p>{offline ? <p className="text-sm font-semibold text-primary">You are using the offline edition. Keep this file and make encrypted backups.</p> : <div className="flex flex-wrap gap-4 text-sm font-semibold text-primary"><a href="/downloads/fourthstep-offline.html" download className="underline underline-offset-4">Download offline edition</a><a href="/downloads/fourthstep-offline.sha256" download className="underline underline-offset-4">SHA-256 checksum</a></div>}<p className="text-xs leading-relaxed text-muted-foreground">Local-file storage behavior varies between browsers. Keep the file in the same location and download encrypted backups regularly. Clearing browser data removes the local vault. The checksum helps identify the downloaded file; it is not an independent security audit.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Keep a recovery copy</h2><p className="text-sm leading-relaxed text-muted-foreground">Download an encrypted backup from Privacy &amp; security or Your inventory. It includes check-ins, unfinished work, and contacts. Restore it in an empty browser profile or the offline edition with your recovery key, or with device unlock on this website. We cannot reset your recovery key or recover answers if you lose every way to unlock.</p><p className="text-sm leading-relaxed text-muted-foreground">If saving fails, locking leaves the page open and shows a recovery warning to protect unsaved work. Suspended browsers can delay auto-lock until you return. After migration, earlier readable copies in device backups or browser history may still exist.</p></section>
    <section className="space-y-3 border-t pt-6"><h2 className="text-xl font-semibold">Evidence, with honest limits</h2><p className="text-sm leading-relaxed text-muted-foreground">The source and automated checks are public. Checks cover encryption, each unlock method, tampering, PIN lockout, failed saves, migration from earlier versions, backups, CSV export safety, and the offline file’s network restrictions. They provide useful evidence, but they are not an independent security review.</p><p className="rounded-xl bg-secondary p-4 text-sm font-semibold">Independent security audit: not yet completed.</p><div className="flex flex-wrap gap-4 text-sm font-semibold text-primary"><a href="https://github.com/gregcastro23/IV" target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 underline underline-offset-4">Inspect the source<ExternalLink className="size-3" /></a><a href="https://github.com/gregcastro23/IV/blob/main/SECURITY.md" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">Security design &amp; review checklist</a><a href="https://github.com/gregcastro23/IV/actions" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">Automated check results</a></div></section>
  </article>
}
